# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the master branch
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: windows-2019

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2

      # Runs a single command using the runners shell
      - name: Install dependencies
        run: |
          vcpkg install tiff:x64-windows
          vcpkg install sqlite3:x64-windows
          Invoke-WebRequest -Uri https://sqlite.org/2018/sqlite-tools-win32-x86-3250100.zip -OutFile sqlite-tools-win32-x86-3250100.zip
          7z x sqlite-tools-win32-x86-3250100.zip
          copy sqlite-tools-win32-x86-3250100/sqlite3.exe .
          
      - name: Build PROJ
        run: |
          git clone --depth=1 -b 6.3 https://github.com/OSGeo/PROJ proj
          cd proj
          mkdir build
          cd build
          copy ..\..\sqlite3.exe .
          $vcpkgPath = [System.IO.Path]::GetDirectoryName((Get-Command vcpkg).Source)
          Write-Host $vcpkgPath
          copy $vcpkgPath\installed\x64-windows\bin\sqlite3.dll .
          $env:PATH="$($pwd.Path);$($env:PATH)"
          cmake -G "Visual Studio 16 2019" -A x64 .. -DCMAKE_BUILD_TYPE=Release -DPROJ_TESTS=OFF -DBUILD_LIBPROJ_SHARED=ON -DCMAKE_TOOLCHAIN_FILE=$vcpkgPath/scripts/buildsystems/vcpkg.cmake -DCMAKE_INSTALL_PREFIX="./install"
          cmake --build . --config Release --target install
          cd ..
          cd ..
          
      # Runs a set of commands using the runners shell
      - name: Build
        run: |
          cd libgeotiff
          mkdir build
          cd build
          cmake -G "Visual Studio 16 2019" -A x64 .. -DBUILD_SHARED_LIBS=ON -DCMAKE_BUILD_TYPE=Release  -DCMAKE_C_FLAGS="/WX" -DCMAKE_CXX_FLAGS="/WX"  -DCMAKE_INSTALL_PREFIX="./install" -DPROJ_INCLUDE_DIR="./install/include" -DPROJ_LIBRARY="./install/lib/proj.lib" -DCMAKE_TOOLCHAIN_FILE=c:/projects/libgeotiff/vcpkg/scripts/buildsystems/vcpkg.cmake
          cmake --build . --config Release --target install
